#!/usr/bin/env python3
'''Domain Artefact.

Usage:
    domain index <file> <index>
'''
from docopt import docopt
import logging
from poulpe import artefact

logging.basicConfig(level=logging.DEBUG)

domain_regex = '(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})'

if __name__ == '__main__':
    arguments = docopt(__doc__)
    fname = arguments['<file>']
    index = arguments['<index>']
    artefact.validate(index, 'domain')
    artefact.index_regex(index, fname, 'domain', domain_regex)
