#!/usr/bin/env python3
'''email Artefact.

Usage:
    email index <file> <index>
'''
from docopt import docopt
import logging
from poulpe import artefact

logging.basicConfig(level=logging.DEBUG)


if __name__ == '__main__':
    arguments = docopt(__doc__)
    fname = arguments['<file>']
    index = arguments['<index>']
    artefact.validate(index, 'email')
    artefact.index_regex(index, fname, 'email',
                         '[\S]+@[\S]+')
