#!/usr/bin/env python3
'''IPv4 Artefact.

Usage:
    IPv4 index <file> <index>
'''
from docopt import docopt
import logging
from poulpe import artefact

logging.basicConfig(level=logging.DEBUG)

base_ten_byte_re = '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
ipv4_regex = '('+(base_ten_byte_re+'\.')*3+base_ten_byte_re+')'

if __name__ == '__main__':
    arguments = docopt(__doc__)
    fname = arguments['<file>']
    index = arguments['<index>']
    artefact.validate(index, 'IPv4')
    artefact.index_regex(index, fname, 'IPv4', ipv4_regex)
