#!/usr/bin/env python3
'''IPv4 Artefact.

Usage:
    IPv4 index <file> <index>
'''
from docopt import docopt
import logging
from poulpe import artefact

logging.basicConfig(level=logging.DEBUG)


if __name__ == '__main__':
    arguments = docopt(__doc__)
    fname = arguments['<file>']
    index = arguments['<index>']
    artefact.validate(index, 'IPv4')
    artefact.index_regex(index, fname, 'IPv4',
                         '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
