#!/usr/bin/env python3
import logging
from glob import glob
import os
from poulpe import cmd
import tempfile
import sys
logging.basicConfig(level=logging.DEBUG)


CWD = os.getcwd()

# List all blobs from commit :
# Code from http://stackoverflow.com/questions/1314950/git-get-all-commits
# -and-blobs-they-created
commit = cmd('git rev-list --max-count=1 --pretty=oneline HEAD').split(' ')[0]
logging.info('processing commit '+commit)
# We take all the files that this commit modified/created
files = cmd('git diff-tree --no-commit-id --name-only -r '+commit).split('\n')
files = [f for f in files if f != '']

# Run all artefacts programs on each file
for art in glob(CWD+'/.git/artefacts/*'):
    logging.info('Running artefact finder for '+art)
    for fname in [f for f in files if not f.startswith('index/')]:
        logging.info('on file : '+fname)
        cmd(art+' index "'+fname+'" '+CWD+'/index')

# Add the index in the appropriate branch
with tempfile.TemporaryDirectory() as tmpdirname:
    logging.info('Cloning into '+tmpdirname)
    os.chdir(tmpdirname)
    cmd('git clone '+CWD+' .')
    if not 'index' in cmd('git branch -a'):
        logging.info('No index branch (This is an error if this is not the first commit)')
        sys.exit()
    logging.info('Commiting index changes')
    cmd('git checkout -b index origin/index')
    cmd('rm -rf index')
    cmd('cp -r '+CWD+'/index index')
    cmd('git add index/**')
    cmd('git commit -m "Index update after commit "'+commit)
    logging.info('Fetching and merging index changes')
    os.chdir(CWD)
    cmd('git fetch '+tmpdirname+' index:index')
    cmd('git add index/**')
    cmd('git stash')
    cmd('git merge index')
    cmd('git stash pop')
# cmd()
